# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-11-02 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import treemap.audit
import treemap.units


class Migration(migrations.Migration):

    dependencies = [
        ('treemap', '0046_auto_20170907_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapFeatureTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            bases=(models.Model, treemap.audit.PendingAuditable, treemap.units.Convertible),
        ),
        migrations.CreateModel(
            name='TreeTag',
            fields=[
                ('mapfeaturetag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='treemap.MapFeatureTag')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treemap.Tree')),
            ],
            bases=('treemap.mapfeaturetag',),
        ),
        migrations.AddField(
            model_name='mapfeaturetag',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treemap.Instance'),
        ),
        migrations.AddField(
            model_name='mapfeaturetag',
            name='map_feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treemap.MapFeature'),
        ),
    ]
