# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-11-02 06:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treemap', '0047_auto_20201102_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapfeaturetag',
            name='instance',
        ),
        migrations.RemoveField(
            model_name='mapfeaturetag',
            name='map_feature',
        ),
        migrations.RemoveField(
            model_name='treetag',
            name='mapfeaturetag_ptr',
        ),
        migrations.RemoveField(
            model_name='treetag',
            name='tree',
        ),
        migrations.DeleteModel(
            name='MapFeatureTag',
        ),
        migrations.DeleteModel(
            name='TreeTag',
        ),
    ]
