# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-12-29 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treemap', '0048_auto_20201102_0109'),
        ('treemap', '0047_instance_itree_region_default_choices_to_list'),
    ]

    operations = [
    ]
