name: Django CI

on:
  push:
    branches: ["develop", "feature/modernize-otm"]
  pull_request:
    branches: ["develop", "feature/modernize-otm"]

jobs:
  build:
    runs-on: ubuntu-26.04
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v4

      - uses: deadsnakes/action@v3.2.0
        with:
          python-version: '3.11'

      - name: Verify Python version
        run: python3.11 --version

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libpython3.11-dev
          python -m pip install --upgrade pip
          pip install wheel
          pip install -r requirements.txt

      - name: Verify Celery Installation
        run: |
          python -c "import celery; print(celery.__version__)"  # Verify Celery import and version

      - name: Run Tests
        run: |
          cd opentreemap
          python manage.py test
